### ISSUE TITLE
安卓客户端rename可以修改后缀

### ISSUE THREAD

**Issue by WXZhao7** [taoky/reccli#1]
真搞不懂抓包，fiddler和证书都配置好了，模拟器内的浏览器倒是https正常抓取，但REC安卓客户端完全搞不懂。大佬有空可以考虑安卓APP :)

**Comment by taoky** [comment]
抱歉最近没有时间去搞，手头也没有 Android 的环境 :(

不过如果有人成功抓包或者逆向找到能完整修改文件名的 API 的话，非常欢迎提 PR！

**Comment by WXZhao7** [comment]
API倒是知道了，不过这个只能重命名文件，总觉得直接加进去过于僵硬。
```python
RecAPI.post("rename_ext", json={"name": new_name, "number": id,})
```

边抄这个项目边试着抓包，最后用GO给Alist写了个驱动。Alist用数据库存储了每个文件的属性，所以调用isFolder决定用哪个api进行重命名就行，单纯的cli就有些困难了，我能想到的是try一个list判断是否为文件夹再决定用哪个api。

请教下登录加密解密那里是如何获取的，可以给个思路吗？我使用的过程中发现登录的时候都是转到统一认证，没提供直接登录的页面欸

**Comment by taoky** [comment]
> API倒是知道了，不过这个只能重命名文件，总觉得直接加进去过于僵硬。
> 
> ```python
> RecAPI.post("rename_ext", json={"name": new_name, "number": id,})
> ```

OK，我有时间的话看一下。

> 边抄这个项目边试着抓包，最后用GO给Alist写了个驱动。Alist用数据库存储了每个文件的属性，所以调用isFolder决定用哪个api进行重命名就行，单纯的cli就有些困难了，我能想到的是try一个list判断是否为文件夹再决定用哪个api。

我之前有打算给 rclone 写 plugin（这样还可以实现相对可靠的 fuse 挂载），自己写的 fuse 总有点不放心……

> 请教下登录加密解密那里是如何获取的，可以给个思路吗？我使用的过程中发现登录的时候都是转到统一认证，没提供直接登录的页面欸

是逆向 PC 客户端的结果。但是我不建议用这个登录，因为需要把统一身份认证凭证发送到 CAS 之外的服务器，可能有安全风险。

**Comment by taoky** [comment]
这个新 API 在 https://github.com/taoky/reccli/commit/9e914663194cdc4eb27a4af775cf9a10ca07d8de 添加了。
